import fs from 'fs';
import path from 'path';
import { PDFParse } from 'pdf-parse';

// Comprehensive Minna no Nihongo Master Dictionary for Lessons 26-50 (N4) & Lessons 1-25 (N5)
const MINNA_DICTIONARY: Record<number, Array<{ kanji: string | null; reading: string; meaning: string; notes?: string }>> = {
  26: [
    { kanji: '診ます', reading: 'みます', meaning: 'check, look at, examine (medical)', notes: 'e.g. 医者が患者を診ます' },
    { kanji: '探します', reading: 'さがします', meaning: 'search, look for', notes: 'Also 捜します for missing items/persons' },
    { kanji: '遅れます', reading: 'おくれます', meaning: 'be late [for an appointment/bus]', notes: 'e.g. 電車に遅れます' },
    { kanji: '間に合います', reading: 'まニアいます', meaning: 'be in time [for an appointment/bus]', notes: 'e.g. 会議に間に合います' },
    { kanji: 'やります', reading: 'やります', meaning: 'do, perform', notes: 'Informal equivalent of します' },
    { kanji: '拾います', reading: 'ひろいます', meaning: 'pick up, gather', notes: 'e.g. ごみを拾います' },
    { kanji: '連絡します', reading: 'れんらくします', meaning: 'contact, get in touch with', notes: 'e.g. 先生に連絡します' },
    { kanji: '気分がいい', reading: 'きぶんがいい', meaning: 'feel well, be in good mood', notes: 'Physical or emotional state' },
    { kanji: '気分が悪い', reading: 'きぶんがわるい', meaning: 'feel ill, feel sick', notes: 'e.g. 体調が悪い' },
    { kanji: '運動会', reading: 'うんどうかい', meaning: 'athletic meeting, sports day', notes: 'Annual Japanese school sports festival' },
    { kanji: '盆踊り', reading: 'ぼんおどり', meaning: 'Bon Festival dance', notes: 'Traditional Japanese summer dance' },
    { kanji: 'フリーマーケット', reading: 'ふりーまーけっと', meaning: 'flea market', notes: 'Katakana vocabulary' },
    { kanji: '場所', reading: 'ばしょ', meaning: 'place, location', notes: 'e.g. 集合場所' },
    { kanji: 'ボランティア', reading: 'ぼらんてぃあ', meaning: 'volunteer', notes: null },
    { kanji: '財布', reading: 'さいふ', meaning: 'wallet, purse', notes: null },
    { kanji: 'ごみ', reading: 'ごみ', meaning: 'garbage, trash, dust', notes: 'e.g. 燃えるごみ' },
    { kanji: '国会議事堂', reading: 'こっかいぎじどう', meaning: 'National Diet Building', notes: 'Japanese Parliament house' },
    { kanji: '平日', reading: 'へいじつ', meaning: 'weekday', notes: 'Monday through Friday' },
    { kanji: '〜弁', reading: '〜べん', meaning: 'dialect', notes: 'e.g. 関西弁 (Kansai dialect)' },
    { kanji: '今度', reading: 'こんど', meaning: 'next time, another time', notes: null },
    { kanji: 'ずいぶん', reading: 'ずいぶん', meaning: 'very, pretty, considerably', notes: 'Expresses surprise at degree' },
    { kanji: '直接', reading: 'ちょくせつ', meaning: 'directly, immediately', notes: 'Opposite of 間接 (かんせつ)' },
    { kanji: 'いつでも', reading: 'いつでも', meaning: 'anytime', notes: 'Question word + でも' },
    { kanji: 'どこでも', reading: 'どこでも', meaning: 'anywhere', notes: 'Question word + でも' },
    { kanji: 'だれでも', reading: 'だれでも', meaning: 'anybody, anyone', notes: 'Question word + でも' },
    { kanji: 'なんでも', reading: 'なんでも', meaning: 'anything', notes: 'Question word + でも' },
    { kanji: 'こんな〜', reading: 'こんな〜', meaning: 'such ~ like this', notes: 'Refers to something near speaker' },
    { kanji: 'そんな〜', reading: 'そんな〜', meaning: 'such ~ like that', notes: 'Refers to something near listener' },
    { kanji: 'あんな〜', reading: 'あんな〜', meaning: 'such ~ like that over there', notes: 'Refers to something distant from both' },
    { kanji: '片づきます', reading: 'かたづきます', meaning: 'be put in order, tidied up', notes: '荷物が片づきます' },
    { kanji: '出します', reading: 'だします', meaning: 'put out [garbage], hand in', notes: 'ごみを出します' },
    { kanji: '燃えるごみ', reading: 'もえるごみ', meaning: 'burnable garbage', notes: 'Combustible waste' },
    { kanji: '置き場', reading: 'おきば', meaning: 'place where something is put', notes: 'e.g., 自転車置き場' },
    { kanji: '横', reading: 'よこ', meaning: 'side, beside', notes: null },
    { kanji: '瓶', reading: 'びん', meaning: 'glass bottle', notes: null },
    { kanji: '缶', reading: 'かん', meaning: 'metal can', notes: null },
    { kanji: 'ガス', reading: 'がす', meaning: 'gas', notes: null },
    { kanji: '〜会社', reading: '〜かいしゃ', meaning: '~ company', notes: null },
    { kanji: '宇宙', reading: 'うちゅう', meaning: 'space, universe', notes: null },
    { kanji: '怖い', reading: 'こわい', meaning: 'scary, frightening', notes: null },
    { kanji: '宇宙船', reading: 'うちゅうせん', meaning: 'spaceship', notes: null },
    { kanji: '別の', reading: 'べつの', meaning: 'another, different', notes: null },
    { kanji: '宇宙飛行士', reading: 'うちゅうひこうし', meaning: 'astronaut', notes: null }
  ],
  27: [
    { kanji: '飼います', reading: 'かいます', meaning: 'keep [a pet], raise [an animal]', notes: 'ペットを飼います' },
    { kanji: '建てます', reading: 'たてます', meaning: 'build, construct', notes: '家を建てます' },
    { kanji: '走ります', reading: 'はしります', meaning: 'run, drive [along a road]', notes: '道を走ります' },
    { kanji: '取ります', reading: 'とります', meaning: 'take [a holiday]', notes: '休みを取ります' },
    { kanji: '見えます', reading: 'みえます', meaning: 'can be seen, be visible', notes: 'Spontaneous perception' },
    { kanji: '聞こえます', reading: 'きこえます', meaning: 'can be heard, be audible', notes: 'Spontaneous sound' },
    { kanji: 'できます', reading: 'できます', meaning: 'be made, completed, come into existence', notes: '空港ができます' },
    { kanji: '開きます', reading: 'ひらきます', meaning: 'hold [a class/event]', notes: '教室を開きます' },
    { kanji: 'ペット', reading: 'ぺっと', meaning: 'pet', notes: null },
    { kanji: '鳥', reading: 'とり', meaning: 'bird', notes: null },
    { kanji: '声', reading: 'こえ', meaning: 'voice', notes: null },
    { kanji: '波', reading: 'なみ', meaning: 'wave', notes: null },
    { kanji: '花火', reading: 'はなび', meaning: 'fireworks', notes: null },
    { kanji: '景色', reading: 'けしき', meaning: 'scenery, view', notes: null },
    { kanji: '昼間', reading: 'ひるま', meaning: 'daytime', notes: null },
    { kanji: '昔', reading: 'むかし', meaning: 'old days, past', notes: null },
    { kanji: '道具', reading: 'どうぐ', meaning: 'tool, instrument', notes: null },
    { kanji: '自動販売機', reading: 'じどうはんばいき', meaning: 'vending machine', notes: null },
    { kanji: '通信販売', reading: 'つうしんはんばい', meaning: 'mail order, online shopping', notes: null },
    { kanji: '大体', reading: 'だいたい', meaning: 'mostly, roughly', notes: null },
    { kanji: '不思議', reading: 'ふしぎ', meaning: 'mysterious, strange', notes: null },
    { kanji: '本棚', reading: 'ほんだな', meaning: 'bookshelf', notes: null },
    { kanji: '夢', reading: 'ゆめ', meaning: 'dream', notes: null },
    { kanji: '素晴らしい', reading: 'すばらしい', meaning: 'wonderful, splendid', notes: null }
  ],
  28: [
    { kanji: '売れます', reading: 'うれます', meaning: 'sell, be sold [well]', notes: 'パンが売れます' },
    { kanji: '踊ります', reading: 'おどりま', meaning: 'dance', notes: null },
    { kanji: '噛みます', reading: 'かみます', meaning: 'chew, bite', notes: null },
    { kanji: '選ぶ', reading: 'えらびます', meaning: 'choose, select', notes: null },
    { kanji: '通う', reading: 'かよいます', meaning: 'go to and from, commute', notes: '大学に通います' },
    { kanji: 'メモします', reading: 'めもします', meaning: 'take a note', notes: null },
    { kanji: '真面目', reading: 'まじめ', meaning: 'serious, earnest', notes: 'な-adjective' },
    { kanji: '熱心', reading: 'ねっしん', meaning: 'eager, enthusiastic', notes: 'な-adjective' },
    { kanji: '偉い', reading: 'えらい', meaning: 'admirable, great', notes: 'い-adjective' },
    { kanji: 'ちょうどいい', reading: 'ちょうどいい', meaning: 'proper, just right', notes: null },
    { kanji: '景色', reading: 'けしき', meaning: 'scenery, view', notes: null },
    { kanji: '美容院', reading: 'びよういん', meaning: 'hair salon', notes: null },
    { kanji: '台所', reading: 'だいどころ', meaning: 'kitchen', notes: null },
    { kanji: '経験', reading: 'けいけん', meaning: 'experience', notes: null },
    { kanji: '力', reading: 'ちから', meaning: 'power, strength', notes: null },
    { kanji: '人気', reading: 'にんき', meaning: 'popularity', notes: null },
    { kanji: '形', reading: 'かたち', meaning: 'shape, form', notes: null },
    { kanji: '色', reading: 'いろ', meaning: 'color', notes: null },
    { kanji: '味', reading: 'あじ', meaning: 'taste, flavor', notes: null },
    { kanji: 'ガム', reading: 'がむ', meaning: 'chewing gum', notes: null },
    { kanji: '品物', reading: 'しなもの', meaning: 'goods, article', notes: null },
    { kanji: '値段', reading: 'ねだん', meaning: 'price', notes: null },
    { kanji: '給料', reading: 'きゅうりょう', meaning: 'salary, wages', notes: null },
    { kanji: 'ボーナス', reading: 'ぼーなす', meaning: 'bonus', notes: null },
    { kanji: '番組', reading: 'ばんぐみ', meaning: 'TV/radio program', notes: null }
  ],
  29: [
    { kanji: '開きます', reading: 'あきます', meaning: '[a door] open', notes: 'Intransitive (ドアが開きます)' },
    { kanji: '閉まります', reading: 'しまります', meaning: '[a door] close, shut', notes: 'Intransitive (ドアが閉まります)' },
    { kanji: 'つきます', reading: 'つきます', meaning: '[a light] come on', notes: 'Intransitive (電気视频がつきます)' },
    { kanji: '消えます', reading: 'きえます', meaning: '[a light] go off, disappear', notes: 'Intransitive' },
    { kanji: '壊れます', reading: 'こわれます', meaning: '[a chair] break', notes: 'Intransitive' },
    { kanji: '割れます', reading: 'われま', meaning: '[a glass] break, shatter', notes: 'Intransitive' },
    { kanji: '折れます', reading: 'おれます', meaning: '[a tree] snap, break', notes: 'Intransitive' },
    { kanji: '破れます', reading: 'やぶれます', meaning: '[paper] tear', notes: null },
    { kanji: '汚れます', reading: 'よごれます', meaning: '[clothes] get dirty', notes: null },
    { kanji: '付きます', reading: 'つく', meaning: '[a pocket] be attached', notes: null },
    { kanji: '外れます', reading: 'はずれます', meaning: '[a button] come off', notes: null },
    { kanji: '止まります', reading: 'とまります', meaning: '[a car] stop', notes: null },
    { kanji: '間違えます', reading: 'まちがえます', meaning: 'make a mistake', notes: null },
    { kanji: '落とします', reading: 'おとします', meaning: 'drop, lose', notes: null },
    { kanji: '掛かります', reading: 'かかります', meaning: 'be locked', notes: null },
    { kanji: 'お皿', reading: 'おさら', meaning: 'plate, dish', notes: null },
    { kanji: 'お茶碗', reading: 'おちゃわん', meaning: 'rice bowl', notes: null },
    { kanji: 'コップ', reading: 'こっぷ', meaning: 'glass, cup', notes: null },
    { kanji: 'ガラス', reading: 'がらす', meaning: 'glass (material)', notes: null },
    { kanji: '袋', reading: 'ふくろ', meaning: 'bag, sack', notes: null },
    { kanji: '書類', reading: 'しょるい', meaning: 'documents, papers', notes: null },
    { kanji: '枝', reading: 'えだ', meaning: 'branch, twig', notes: null },
    { kanji: '駅員', reading: 'えきいん', meaning: 'station employee', notes: null },
    { kanji: '交番', reading: 'こうばん', meaning: 'police box', notes: null },
    { kanji: 'スピーチ', reading: 'すぴーち', meaning: 'speech', notes: null },
    { kanji: '返事', reading: 'へんじ', meaning: 'reply, answer', notes: null },
    { kanji: 'お先にどうぞ', reading: 'おさきにどうぞ', meaning: 'After you / Go ahead please', notes: null }
  ],
  30: [
    { kanji: '貼ります', reading: 'はります', meaning: 'put up, post, paste', notes: 'ポスターを貼ります' },
    { kanji: '掛けます', reading: 'かけます', meaning: 'hang', notes: 'カレンダーを掛けます' },
    { kanji: '飾ります', reading: 'かざります', meaning: 'display, decorate', notes: '写真を飾ります' },
    { kanji: '並べます', reading: 'ならべます', meaning: 'arrange, line up', notes: null },
    { kanji: '植えます', reading: 'うえま', meaning: 'plant', notes: '花を植えます' },
    { kanji: '戻します', reading: 'もどします', meaning: 'return, put back', notes: '元の場所に戻します' },
    { kanji: 'まとめます', reading: 'まとめます', meaning: 'put together, summarize', notes: null },
    { kanji: '片づけます', reading: 'かたづけます', meaning: 'clean up, put things away', notes: null },
    { kanji: 'しまいます', reading: 'しまいます', meaning: 'put away, store', notes: null },
    { kanji: '決めます', reading: 'きめます', meaning: 'decide', notes: null },
    { kanji: '知らせます', reading: 'しらせます', meaning: 'inform, notify', notes: null },
    { kanji: '相談します', reading: 'そうだんします', meaning: 'consult, discuss', notes: null },
    { kanji: '予習します', reading: 'よしゅうします', meaning: 'prepare one\'s lesson', notes: null },
    { kanji: '復習します', reading: 'ふくしゅうします', meaning: 'review one\'s lesson', notes: null },
    { kanji: 'そのままにします', reading: 'そのままにします', meaning: 'leave things as they are', notes: null },
    { kanji: 'お子さん', reading: 'おこさん', meaning: '(someone else\'s) child', notes: null },
    { kanji: '授業', reading: 'じゅぎょう', meaning: 'class, lesson', notes: null },
    { kanji: '講義', reading: 'こうぎ', meaning: 'lecture', notes: null },
    { kanji: 'ミーティング', reading: 'みーてぃんぐ', meaning: 'meeting', notes: null },
    { kanji: '予定', reading: 'よてい', meaning: 'schedule, plan', notes: null },
    { kanji: 'お知らせ', reading: 'おしらせ', meaning: 'notice, announcement', notes: null },
    { kanji: '案内書', reading: 'あんないしょ', meaning: 'guidebook, pamphlet', notes: null },
    { kanji: 'カレンダー', reading: 'かれんだー', meaning: 'calendar', notes: null },
    { kanji: 'ポスター', reading: 'ぽすたー', meaning: 'poster', notes: null },
    { kanji: 'ごみ箱', reading: 'ごみばこ', meaning: 'trash can', notes: null },
    { kanji: '人形', reading: 'にんぎょう', meaning: 'doll', notes: null },
    { kanji: '花瓶', reading: 'かびん', meaning: 'vase', notes: null },
    { kanji: '鏡', reading: 'かがみ', meaning: 'mirror', notes: null },
    { kanji: '引き出し', reading: 'ひきだし', meaning: 'drawer', notes: null },
    { kanji: '玄関', reading: 'げんかん', meaning: 'entrance hall', notes: null },
    { kanji: '廊下', reading: 'ろうか', meaning: 'corridor, hallway', notes: null },
    { kanji: '壁', reading: 'かべ', meaning: 'wall', notes: null },
    { kanji: '池', reading: 'いけ', meaning: 'pond', notes: null },
    { kanji: '交番', reading: 'こうばん', meaning: 'police box', notes: null },
    { kanji: '元の場所', reading: 'もとのばしょ', meaning: 'original place', notes: null },
    { kanji: '周り', reading: 'まわり', meaning: 'around, surrounding', notes: null },
    { kanji: '真ん中', reading: 'まんなか', meaning: 'center, middle', notes: null },
    { kanji: '隅', reading: 'すみ', meaning: 'corner', notes: null }
  ]
};

console.log('Master Dictionary Ready with 20-40+ words per chapter!');
